// <auto-generated />
using System;
using BookingBoardGames.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingBoardGames.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<double>("Latitude")
                        .HasColumnType("float")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("float")
                        .HasColumnName("longitude");

                    b.Property<string>("MainName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("main_name");

                    b.Property<string>("Names")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("names");

                    b.HasKey("CityId");

                    b.ToTable("cities");
                });

            modelBuilder.Entity("Conversation", b =>
                {
                    b.Property<int>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConversationId"));

                    b.HasKey("ConversationId");

                    b.ToTable("conversations");
                });

            modelBuilder.Entity("ConversationParticipant", b =>
                {
                    b.Property<int>("ConversationId")
                        .HasColumnType("int")
                        .HasColumnName("conversation_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<DateTime?>("LastMessageReadTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_message_read_time");

                    b.Property<int>("UnreadMessagesCount")
                        .HasColumnType("int")
                        .HasColumnName("unread_messages_count");

                    b.HasKey("ConversationId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("conversation_participants");
                });

            modelBuilder.Entity("Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("image");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<int>("MaximumPlayerNumber")
                        .HasColumnType("int")
                        .HasColumnName("maximum_player_number");

                    b.Property<int>("MinimumPlayerNumber")
                        .HasColumnType("int")
                        .HasColumnName("minimum_player_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    b.Property<decimal>("PricePerDay")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("games");
                });

            modelBuilder.Entity("Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<int>("ConversationId")
                        .HasColumnType("int")
                        .HasColumnName("conversation_id");

                    b.Property<string>("MessageCategory")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("MessageContentAsString")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message_content_as_string");

                    b.Property<int>("MessageReceiverId")
                        .HasColumnType("int")
                        .HasColumnName("message_receiver_id");

                    b.Property<int>("MessageSenderId")
                        .HasColumnType("int")
                        .HasColumnName("message_sender_id");

                    b.Property<DateTime>("MessageSentTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("message_sent_time");

                    b.HasKey("MessageId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("MessageReceiverId");

                    b.HasIndex("MessageSenderId");

                    b.ToTable("messages");

                    b.HasDiscriminator<string>("MessageCategory").HasValue("Message");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Payment", b =>
                {
                    b.Property<int>("TransactionIdentifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionIdentifier"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("client_id");

                    b.Property<DateTime?>("DateConfirmedBuyer")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_confirmed_buyer");

                    b.Property<DateTime?>("DateConfirmedSeller")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_confirmed_seller");

                    b.Property<DateTime?>("DateOfTransaction")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_of_transaction");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    b.Property<decimal>("PaidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("paid_amount");

                    b.Property<string>("PaymentCategory")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payment_method");

                    b.Property<int>("PaymentState")
                        .HasColumnType("int")
                        .HasColumnName("payment_state");

                    b.Property<string>("ReceiptFilePath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("receipt_file_path");

                    b.Property<int>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    b.HasKey("TransactionIdentifier");

                    b.HasIndex("ClientId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("RequestId");

                    b.ToTable("payments");

                    b.HasDiscriminator<string>("PaymentCategory").HasValue("Standard");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Rental", b =>
                {
                    b.Property<int>("RentalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RentalId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_date");

                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("game_id");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    b.Property<int?>("PaymentTransactionIdentifier")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.Property<decimal?>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_price");

                    b.HasKey("RentalId");

                    b.HasIndex("ClientId");

                    b.HasIndex("GameId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PaymentTransactionIdentifier");

                    b.ToTable("rentals");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("avatar_url");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("balance");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("bit")
                        .HasColumnName("is_suspended");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("street");

                    b.Property<string>("StreetNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("street_number");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("CashAgreementMessage", b =>
                {
                    b.HasBaseType("Message");

                    b.Property<int>("CashPaymentId")
                        .HasColumnType("int")
                        .HasColumnName("cash_payment_id");

                    b.Property<bool>("IsCashAgreementAcceptedByBuyer")
                        .HasColumnType("bit")
                        .HasColumnName("is_cash_agreement_accepted_by_buyer");

                    b.Property<bool>("IsCashAgreementAcceptedBySeller")
                        .HasColumnType("bit")
                        .HasColumnName("is_cash_agreement_accepted_by_seller");

                    b.Property<bool>("IsCashAgreementResolved")
                        .HasColumnType("bit")
                        .HasColumnName("is_cash_agreement_resolved");

                    b.HasIndex("CashPaymentId");

                    b.ToTable("messages");

                    b.HasDiscriminator().HasValue("CashAgreement");
                });

            modelBuilder.Entity("ImageMessage", b =>
                {
                    b.HasBaseType("Message");

                    b.Property<string>("MessageImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message_image_url");

                    b.ToTable("messages");

                    b.HasDiscriminator().HasValue("Image");
                });

            modelBuilder.Entity("RentalRequestMessage", b =>
                {
                    b.HasBaseType("Message");

                    b.Property<bool>("IsRequestAccepted")
                        .HasColumnType("bit")
                        .HasColumnName("is_request_accepted");

                    b.Property<bool>("IsRequestResolved")
                        .HasColumnType("bit")
                        .HasColumnName("is_request_resolved");

                    b.Property<int>("RentalRequestId")
                        .HasColumnType("int")
                        .HasColumnName("rental_request_id");

                    b.Property<string>("RequestContent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("request_content");

                    b.HasIndex("RentalRequestId");

                    b.ToTable("messages");

                    b.HasDiscriminator().HasValue("RentalRequest");
                });

            modelBuilder.Entity("SystemMessage", b =>
                {
                    b.HasBaseType("Message");

                    b.Property<string>("MessageContent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message_content");

                    b.ToTable("messages");

                    b.HasDiscriminator().HasValue("System");
                });

            modelBuilder.Entity("TextMessage", b =>
                {
                    b.HasBaseType("Message");

                    b.Property<string>("TextMessageContent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("text_message_content");

                    b.ToTable("messages");

                    b.HasDiscriminator().HasValue("Text");
                });

            modelBuilder.Entity("HistoryPayment", b =>
                {
                    b.HasBaseType("Payment");

                    b.Property<string>("GameName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("game_name");

                    b.Property<string>("OwnerName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("owner_name");

                    b.ToTable("payments");

                    b.HasDiscriminator().HasValue("History");
                });

            modelBuilder.Entity("ConversationParticipant", b =>
                {
                    b.HasOne("Conversation", "Conversation")
                        .WithMany("Participants")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany("Conversations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Game", b =>
                {
                    b.HasOne("User", "Owner")
                        .WithMany("OwnedGames")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Message", b =>
                {
                    b.HasOne("Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "Receiver")
                        .WithMany()
                        .HasForeignKey("MessageReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("User", "Sender")
                        .WithMany()
                        .HasForeignKey("MessageSenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Payment", b =>
                {
                    b.HasOne("User", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Rental", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Owner");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Rental", b =>
                {
                    b.HasOne("User", "Client")
                        .WithMany("RentalsAsClient")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Game", "Game")
                        .WithMany("Rentals")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "Owner")
                        .WithMany("RentalsAsOwner")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Payment", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentTransactionIdentifier");

                    b.Navigation("Client");

                    b.Navigation("Game");

                    b.Navigation("Owner");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("CashAgreementMessage", b =>
                {
                    b.HasOne("Payment", "CashPayment")
                        .WithMany()
                        .HasForeignKey("CashPaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CashPayment");
                });

            modelBuilder.Entity("RentalRequestMessage", b =>
                {
                    b.HasOne("Rental", "RentalRequest")
                        .WithMany("Messages")
                        .HasForeignKey("RentalRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RentalRequest");
                });

            modelBuilder.Entity("Conversation", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Game", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("Rental", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("Conversations");

                    b.Navigation("OwnedGames");

                    b.Navigation("RentalsAsClient");

                    b.Navigation("RentalsAsOwner");
                });
#pragma warning restore 612, 618
        }
    }
}
