name: PR Compilation Check

on:
  pull_request:

jobs:
  build:
    name: Compile and Test Check
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore BoardGamesApp/BookingBoardGames/BookingBoardGames.sln

    - name: Build Solution
      run: dotnet build BoardGamesApp/BookingBoardGames/BookingBoardGames.sln --no-restore -c Release -p:PublishReadyToRun=false

    - name: Run Tests
      run: dotnet test BoardGamesApp/BookingBoardGames/BookingBoardGames.sln --no-build -c Release